
name: hjk-test-v1
description: 현정이의 테스트

on: [push]

jobs:
  hello_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Run Python script
        run: python test.py
