name: hjk-test-v1
description: 현정이의 테스트

inputs:
  test-variable:
    description: "카카오 사용자 입력 변수 테스트"
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MY_INPUT_VAR: ${{ inputs.test-variable }}
